//The list of all the player textures, both the default models and the partial textures used for customization

export interface CustomBodyResources {
    level: number;
    items: BodyResourceDescriptionListInterface;
}

export interface PrefabResources {
    category: string;
    items: BodyResourceDescriptionListInterface;
}

export interface BodyResourceDescriptionListInterface {
    [key: string]: string;
}

export interface CharacterListInterface {
    prefab: PrefabResources[];
    custom: CustomBodyResources[];
}

export const PLAYER_RESOURCES: BodyResourceDescriptionListInterface = {
    male1: "resources/characters/pipoya/Male 01-1.png",
    male2: "resources/characters/pipoya/Male 02-2.png",
    male3: "resources/characters/pipoya/Male 03-4.png",
    male4: "resources/characters/pipoya/Male 09-1.png",
    male5: "resources/characters/pipoya/Male 10-3.png",
    male6: "resources/characters/pipoya/Male 17-2.png",
    male7: "resources/characters/pipoya/Male 18-1.png",
    male8: "resources/characters/pipoya/Male 16-4.png",
    male9: "resources/characters/pipoya/Male 07-2.png",
    male10: "resources/characters/pipoya/Male 05-3.png",
    male11: "resources/characters/pipoya/Teacher male 02.png",
    male12: "resources/characters/pipoya/su4 Student male 12.png",

    Female1: "resources/characters/pipoya/Female 01-1.png",
    Female2: "resources/characters/pipoya/Female 02-2.png",
    Female3: "resources/characters/pipoya/Female 03-4.png",
    Female4: "resources/characters/pipoya/Female 09-1.png",
    Female5: "resources/characters/pipoya/Female 10-3.png",
    Female6: "resources/characters/pipoya/Female 17-2.png",
    Female7: "resources/characters/pipoya/Female 18-1.png",
    Female8: "resources/characters/pipoya/Female 16-4.png",
    Female9: "resources/characters/pipoya/Female 07-2.png",
    Female10: "resources/characters/pipoya/Female 05-3.png",
    Female11: "resources/characters/pipoya/Teacher fmale 02.png",
    Female12: "resources/characters/pipoya/su4 Student fmale 12.png",
};

const COLOR_RESOURCES: BodyResourceDescriptionListInterface = {
    color_1: "resources/customisation/character_color/character_color0.png",
    color_2: "resources/customisation/character_color/character_color1.png",
    color_3: "resources/customisation/character_color/character_color2.png",
    color_4: "resources/customisation/character_color/character_color3.png",
    color_5: "resources/customisation/character_color/character_color4.png",
    color_6: "resources/customisation/character_color/character_color5.png",
    color_7: "resources/customisation/character_color/character_color6.png",
    color_8: "resources/customisation/character_color/character_color7.png",
    color_9: "resources/customisation/character_color/character_color8.png",
    color_10: "resources/customisation/character_color/character_color9.png",
    color_11: "resources/customisation/character_color/character_color10.png",
    color_12: "resources/customisation/character_color/character_color11.png",
    color_13: "resources/customisation/character_color/character_color12.png",
    color_14: "resources/customisation/character_color/character_color13.png",
    color_15: "resources/customisation/character_color/character_color14.png",
    color_16: "resources/customisation/character_color/character_color15.png",
    color_17: "resources/customisation/character_color/character_color16.png",
    color_18: "resources/customisation/character_color/character_color17.png",
    color_19: "resources/customisation/character_color/character_color18.png",
    color_20: "resources/customisation/character_color/character_color19.png",
    color_21: "resources/customisation/character_color/character_color20.png",
    color_22: "resources/customisation/character_color/character_color21.png",
    color_23: "resources/customisation/character_color/character_color22.png",
    color_24: "resources/customisation/character_color/character_color23.png",
    color_25: "resources/customisation/character_color/character_color24.png",
    color_26: "resources/customisation/character_color/character_color25.png",
    color_27: "resources/customisation/character_color/character_color26.png",
    color_28: "resources/customisation/character_color/character_color27.png",
    color_29: "resources/customisation/character_color/character_color28.png",
    color_30: "resources/customisation/character_color/character_color29.png",
    color_31: "resources/customisation/character_color/character_color30.png",
    color_32: "resources/customisation/character_color/character_color31.png",
    color_33: "resources/customisation/character_color/character_color32.png",
};

const EYES_RESOURCES: BodyResourceDescriptionListInterface = {
    eyes_1: "resources/customisation/character_eyes/character_eyes1.png",
    eyes_2: "resources/customisation/character_eyes/character_eyes2.png",
    eyes_3: "resources/customisation/character_eyes/character_eyes3.png",
    eyes_4: "resources/customisation/character_eyes/character_eyes4.png",
    eyes_5: "resources/customisation/character_eyes/character_eyes5.png",
    eyes_6: "resources/customisation/character_eyes/character_eyes6.png",
    eyes_7: "resources/customisation/character_eyes/character_eyes7.png",
    eyes_8: "resources/customisation/character_eyes/character_eyes8.png",
    eyes_9: "resources/customisation/character_eyes/character_eyes9.png",
    eyes_10: "resources/customisation/character_eyes/character_eyes10.png",
    eyes_11: "resources/customisation/character_eyes/character_eyes11.png",
    eyes_12: "resources/customisation/character_eyes/character_eyes12.png",
    eyes_13: "resources/customisation/character_eyes/character_eyes13.png",
    eyes_14: "resources/customisation/character_eyes/character_eyes14.png",
    eyes_15: "resources/customisation/character_eyes/character_eyes15.png",
    eyes_16: "resources/customisation/character_eyes/character_eyes16.png",
    eyes_17: "resources/customisation/character_eyes/character_eyes17.png",
    eyes_18: "resources/customisation/character_eyes/character_eyes18.png",
    eyes_19: "resources/customisation/character_eyes/character_eyes19.png",
    eyes_20: "resources/customisation/character_eyes/character_eyes20.png",
    eyes_21: "resources/customisation/character_eyes/character_eyes21.png",
    eyes_22: "resources/customisation/character_eyes/character_eyes22.png",
    eyes_23: "resources/customisation/character_eyes/character_eyes23.png",
    eyes_24: "resources/customisation/character_eyes/character_eyes24.png",
    eyes_25: "resources/customisation/character_eyes/character_eyes25.png",
    eyes_26: "resources/customisation/character_eyes/character_eyes26.png",
    eyes_27: "resources/customisation/character_eyes/character_eyes27.png",
    eyes_28: "resources/customisation/character_eyes/character_eyes28.png",
    eyes_29: "resources/customisation/character_eyes/character_eyes29.png",
    eyes_30: "resources/customisation/character_eyes/character_eyes30.png",
};

const HAIR_RESOURCES: BodyResourceDescriptionListInterface = {
    hair_1: "resources/customisation/character_hairs/character_hairs0.png",
    hair_2: "resources/customisation/character_hairs/character_hairs1.png",
    hair_3: "resources/customisation/character_hairs/character_hairs2.png",
    hair_4: "resources/customisation/character_hairs/character_hairs3.png",
    hair_5: "resources/customisation/character_hairs/character_hairs4.png",
    hair_6: "resources/customisation/character_hairs/character_hairs5.png",
    hair_7: "resources/customisation/character_hairs/character_hairs6.png",
    hair_8: "resources/customisation/character_hairs/character_hairs7.png",
    hair_9: "resources/customisation/character_hairs/character_hairs8.png",
    hair_10: "resources/customisation/character_hairs/character_hairs9.png",
    hair_11: "resources/customisation/character_hairs/character_hairs10.png",
    hair_12: "resources/customisation/character_hairs/character_hairs11.png",
    hair_13: "resources/customisation/character_hairs/character_hairs12.png",
    hair_14: "resources/customisation/character_hairs/character_hairs13.png",
    hair_15: "resources/customisation/character_hairs/character_hairs14.png",
    hair_16: "resources/customisation/character_hairs/character_hairs15.png",
    hair_17: "resources/customisation/character_hairs/character_hairs16.png",
    hair_18: "resources/customisation/character_hairs/character_hairs17.png",
    hair_19: "resources/customisation/character_hairs/character_hairs18.png",
    hair_20: "resources/customisation/character_hairs/character_hairs19.png",
    hair_21: "resources/customisation/character_hairs/character_hairs20.png",
    hair_22: "resources/customisation/character_hairs/character_hairs21.png",
    hair_23: "resources/customisation/character_hairs/character_hairs22.png",
    hair_24: "resources/customisation/character_hairs/character_hairs23.png",
    hair_25: "resources/customisation/character_hairs/character_hairs24.png",
    hair_26: "resources/customisation/character_hairs/character_hairs25.png",
    hair_27: "resources/customisation/character_hairs/character_hairs26.png",
    hair_28: "resources/customisation/character_hairs/character_hairs27.png",
    hair_29: "resources/customisation/character_hairs/character_hairs28.png",
    hair_30: "resources/customisation/character_hairs/character_hairs29.png",
    hair_31: "resources/customisation/character_hairs/character_hairs30.png",
    hair_32: "resources/customisation/character_hairs/character_hairs31.png",
    hair_33: "resources/customisation/character_hairs/character_hairs32.png",
    hair_34: "resources/customisation/character_hairs/character_hairs33.png",
    hair_35: "resources/customisation/character_hairs/character_hairs34.png",
    hair_36: "resources/customisation/character_hairs/character_hairs35.png",
    hair_37: "resources/customisation/character_hairs/character_hairs36.png",
    hair_38: "resources/customisation/character_hairs/character_hairs37.png",
    hair_39: "resources/customisation/character_hairs/character_hairs38.png",
    hair_40: "resources/customisation/character_hairs/character_hairs39.png",
    hair_41: "resources/customisation/character_hairs/character_hairs40.png",
    hair_42: "resources/customisation/character_hairs/character_hairs41.png",
    hair_43: "resources/customisation/character_hairs/character_hairs42.png",
    hair_44: "resources/customisation/character_hairs/character_hairs43.png",
    hair_45: "resources/customisation/character_hairs/character_hairs44.png",
    hair_46: "resources/customisation/character_hairs/character_hairs45.png",
    hair_47: "resources/customisation/character_hairs/character_hairs46.png",
    hair_48: "resources/customisation/character_hairs/character_hairs47.png",
    hair_49: "resources/customisation/character_hairs/character_hairs48.png",
    hair_50: "resources/customisation/character_hairs/character_hairs49.png",
    hair_51: "resources/customisation/character_hairs/character_hairs50.png",
    hair_52: "resources/customisation/character_hairs/character_hairs51.png",
    hair_53: "resources/customisation/character_hairs/character_hairs52.png",
    hair_54: "resources/customisation/character_hairs/character_hairs53.png",
    hair_55: "resources/customisation/character_hairs/character_hairs54.png",
    hair_56: "resources/customisation/character_hairs/character_hairs55.png",
    hair_57: "resources/customisation/character_hairs/character_hairs56.png",
    hair_58: "resources/customisation/character_hairs/character_hairs57.png",
    hair_59: "resources/customisation/character_hairs/character_hairs58.png",
    hair_60: "resources/customisation/character_hairs/character_hairs59.png",
    hair_61: "resources/customisation/character_hairs/character_hairs60.png",
    hair_62: "resources/customisation/character_hairs/character_hairs61.png",
    hair_63: "resources/customisation/character_hairs/character_hairs62.png",
    hair_64: "resources/customisation/character_hairs/character_hairs63.png",
    hair_65: "resources/customisation/character_hairs/character_hairs64.png",
    hair_66: "resources/customisation/character_hairs/character_hairs65.png",
    hair_67: "resources/customisation/character_hairs/character_hairs66.png",
    hair_68: "resources/customisation/character_hairs/character_hairs67.png",
    hair_69: "resources/customisation/character_hairs/character_hairs68.png",
    hair_70: "resources/customisation/character_hairs/character_hairs69.png",
    hair_71: "resources/customisation/character_hairs/character_hairs70.png",
    hair_72: "resources/customisation/character_hairs/character_hairs71.png",
    hair_73: "resources/customisation/character_hairs/character_hairs72.png",
    hair_74: "resources/customisation/character_hairs/character_hairs73.png",
};

const CLOTHES_RESOURCES: BodyResourceDescriptionListInterface = {
    clothes_1: "resources/customisation/character_clothes/character_clothes0.png",
    clothes_2: "resources/customisation/character_clothes/character_clothes1.png",
    clothes_3: "resources/customisation/character_clothes/character_clothes2.png",
    clothes_4: "resources/customisation/character_clothes/character_clothes3.png",
    clothes_5: "resources/customisation/character_clothes/character_clothes4.png",
    clothes_6: "resources/customisation/character_clothes/character_clothes5.png",
    clothes_7: "resources/customisation/character_clothes/character_clothes6.png",
    clothes_8: "resources/customisation/character_clothes/character_clothes7.png",
    clothes_9: "resources/customisation/character_clothes/character_clothes8.png",
    clothes_10: "resources/customisation/character_clothes/character_clothes9.png",
    clothes_11: "resources/customisation/character_clothes/character_clothes10.png",
    clothes_12: "resources/customisation/character_clothes/character_clothes11.png",
    clothes_13: "resources/customisation/character_clothes/character_clothes12.png",
    clothes_14: "resources/customisation/character_clothes/character_clothes13.png",
    clothes_15: "resources/customisation/character_clothes/character_clothes14.png",
    clothes_16: "resources/customisation/character_clothes/character_clothes15.png",
    clothes_17: "resources/customisation/character_clothes/character_clothes16.png",
    clothes_18: "resources/customisation/character_clothes/character_clothes17.png",
    clothes_19: "resources/customisation/character_clothes/character_clothes18.png",
    clothes_20: "resources/customisation/character_clothes/character_clothes19.png",
    clothes_21: "resources/customisation/character_clothes/character_clothes20.png",
    clothes_22: "resources/customisation/character_clothes/character_clothes21.png",
    clothes_23: "resources/customisation/character_clothes/character_clothes22.png",
    clothes_24: "resources/customisation/character_clothes/character_clothes23.png",
    clothes_25: "resources/customisation/character_clothes/character_clothes24.png",
    clothes_26: "resources/customisation/character_clothes/character_clothes25.png",
    clothes_27: "resources/customisation/character_clothes/character_clothes26.png",
    clothes_28: "resources/customisation/character_clothes/character_clothes27.png",
    clothes_29: "resources/customisation/character_clothes/character_clothes28.png",
    clothes_30: "resources/customisation/character_clothes/character_clothes29.png",
    clothes_31: "resources/customisation/character_clothes/character_clothes30.png",
    clothes_32: "resources/customisation/character_clothes/character_clothes31.png",
    clothes_33: "resources/customisation/character_clothes/character_clothes32.png",
    clothes_34: "resources/customisation/character_clothes/character_clothes33.png",
    clothes_35: "resources/customisation/character_clothes/character_clothes34.png",
    clothes_36: "resources/customisation/character_clothes/character_clothes35.png",
    clothes_37: "resources/customisation/character_clothes/character_clothes36.png",
    clothes_38: "resources/customisation/character_clothes/character_clothes37.png",
    clothes_39: "resources/customisation/character_clothes/character_clothes38.png",
    clothes_40: "resources/customisation/character_clothes/character_clothes39.png",
    clothes_41: "resources/customisation/character_clothes/character_clothes40.png",
    clothes_42: "resources/customisation/character_clothes/character_clothes41.png",
    clothes_43: "resources/customisation/character_clothes/character_clothes42.png",
    clothes_44: "resources/customisation/character_clothes/character_clothes43.png",
    clothes_45: "resources/customisation/character_clothes/character_clothes44.png",
    clothes_46: "resources/customisation/character_clothes/character_clothes45.png",
    clothes_47: "resources/customisation/character_clothes/character_clothes46.png",
    clothes_48: "resources/customisation/character_clothes/character_clothes47.png",
    clothes_49: "resources/customisation/character_clothes/character_clothes48.png",
    clothes_50: "resources/customisation/character_clothes/character_clothes49.png",
    clothes_51: "resources/customisation/character_clothes/character_clothes50.png",
    clothes_52: "resources/customisation/character_clothes/character_clothes51.png",
    clothes_53: "resources/customisation/character_clothes/character_clothes52.png",
    clothes_54: "resources/customisation/character_clothes/character_clothes53.png",
    clothes_55: "resources/customisation/character_clothes/character_clothes54.png",
    clothes_56: "resources/customisation/character_clothes/character_clothes55.png",
    clothes_57: "resources/customisation/character_clothes/character_clothes56.png",
    clothes_58: "resources/customisation/character_clothes/character_clothes57.png",
    clothes_59: "resources/customisation/character_clothes/character_clothes58.png",
    clothes_60: "resources/customisation/character_clothes/character_clothes59.png",
    clothes_61: "resources/customisation/character_clothes/character_clothes60.png",
    clothes_62: "resources/customisation/character_clothes/character_clothes61.png",
    clothes_63: "resources/customisation/character_clothes/character_clothes62.png",
    clothes_64: "resources/customisation/character_clothes/character_clothes63.png",
    clothes_65: "resources/customisation/character_clothes/character_clothes64.png",
    clothes_66: "resources/customisation/character_clothes/character_clothes65.png",
    clothes_67: "resources/customisation/character_clothes/character_clothes66.png",
    clothes_68: "resources/customisation/character_clothes/character_clothes67.png",
    clothes_69: "resources/customisation/character_clothes/character_clothes68.png",
    clothes_70: "resources/customisation/character_clothes/character_clothes69.png",
    clothes_pride_shirt: "resources/customisation/character_clothes/pride_shirt.png",
    clothes_black_hoodie: "resources/customisation/character_clothes/black_hoodie.png",
    clothes_white_hoodie: "resources/customisation/character_clothes/white_hoodie.png",
    clothes_engelbert: "resources/customisation/character_clothes/engelbert.png",
};

const HATS_RESOURCES: BodyResourceDescriptionListInterface = {
    hats_1: "resources/customisation/character_hats/character_hats1.png",
    hats_2: "resources/customisation/character_hats/character_hats2.png",
    hats_3: "resources/customisation/character_hats/character_hats3.png",
    hats_4: "resources/customisation/character_hats/character_hats4.png",
    hats_5: "resources/customisation/character_hats/character_hats5.png",
    hats_6: "resources/customisation/character_hats/character_hats6.png",
    hats_7: "resources/customisation/character_hats/character_hats7.png",
    hats_8: "resources/customisation/character_hats/character_hats8.png",
    hats_9: "resources/customisation/character_hats/character_hats9.png",
    hats_10: "resources/customisation/character_hats/character_hats10.png",
    hats_11: "resources/customisation/character_hats/character_hats11.png",
    hats_12: "resources/customisation/character_hats/character_hats12.png",
    hats_13: "resources/customisation/character_hats/character_hats13.png",
    hats_14: "resources/customisation/character_hats/character_hats14.png",
    hats_15: "resources/customisation/character_hats/character_hats15.png",
    hats_16: "resources/customisation/character_hats/character_hats16.png",
    hats_17: "resources/customisation/character_hats/character_hats17.png",
    hats_18: "resources/customisation/character_hats/character_hats18.png",
    hats_19: "resources/customisation/character_hats/character_hats19.png",
    hats_20: "resources/customisation/character_hats/character_hats20.png",
    hats_21: "resources/customisation/character_hats/character_hats21.png",
    hats_22: "resources/customisation/character_hats/character_hats22.png",
    hats_23: "resources/customisation/character_hats/character_hats23.png",
    hats_24: "resources/customisation/character_hats/character_hats24.png",
    hats_25: "resources/customisation/character_hats/character_hats25.png",
    hats_26: "resources/customisation/character_hats/character_hats26.png",
    tinfoil_hat1: "resources/customisation/character_hats/tinfoil_hat1.png",
};

const ACCESSORIES_RESOURCES: BodyResourceDescriptionListInterface = {
    accessory_1: "resources/customisation/character_accessories/character_accessories1.png",
    accessory_2: "resources/customisation/character_accessories/character_accessories2.png",
    accessory_3: "resources/customisation/character_accessories/character_accessories3.png",
    accessory_4: "resources/customisation/character_accessories/character_accessories4.png",
    accessory_5: "resources/customisation/character_accessories/character_accessories5.png",
    accessory_6: "resources/customisation/character_accessories/character_accessories6.png",
    accessory_7: "resources/customisation/character_accessories/character_accessories7.png",
    accessory_8: "resources/customisation/character_accessories/character_accessories8.png",
    accessory_9: "resources/customisation/character_accessories/character_accessories9.png",
    accessory_10: "resources/customisation/character_accessories/character_accessories10.png",
    accessory_11: "resources/customisation/character_accessories/character_accessories11.png",
    accessory_12: "resources/customisation/character_accessories/character_accessories12.png",
    accessory_13: "resources/customisation/character_accessories/character_accessories13.png",
    accessory_14: "resources/customisation/character_accessories/character_accessories14.png",
    accessory_15: "resources/customisation/character_accessories/character_accessories15.png",
    accessory_16: "resources/customisation/character_accessories/character_accessories16.png",
    accessory_17: "resources/customisation/character_accessories/character_accessories17.png",
    accessory_18: "resources/customisation/character_accessories/character_accessories18.png",
    accessory_19: "resources/customisation/character_accessories/character_accessories19.png",
    accessory_20: "resources/customisation/character_accessories/character_accessories20.png",
    accessory_21: "resources/customisation/character_accessories/character_accessories21.png",
    accessory_22: "resources/customisation/character_accessories/character_accessories22.png",
    accessory_23: "resources/customisation/character_accessories/character_accessories23.png",
    accessory_24: "resources/customisation/character_accessories/character_accessories24.png",
    accessory_25: "resources/customisation/character_accessories/character_accessories25.png",
    accessory_26: "resources/customisation/character_accessories/character_accessories26.png",
    accessory_27: "resources/customisation/character_accessories/character_accessories27.png",
    accessory_28: "resources/customisation/character_accessories/character_accessories28.png",
    accessory_29: "resources/customisation/character_accessories/character_accessories29.png",
    accessory_30: "resources/customisation/character_accessories/character_accessories30.png",
    accessory_31: "resources/customisation/character_accessories/character_accessories31.png",
    accessory_32: "resources/customisation/character_accessories/character_accessories32.png",
    accessory_mate_bottle: "resources/customisation/character_accessories/mate_bottle1.png",
    accessory_mask: "resources/customisation/character_accessories/mask.png",
};

export const LAYERS: CharacterListInterface = {
    prefab: [
        {
            category: "Pre-built characters",
            items: PLAYER_RESOURCES,
        },
    ],
    custom: [
        {
            level: 0,
            items: COLOR_RESOURCES,
        },
        {
            level: 1,
            items: EYES_RESOURCES,
        },
        {
            level: 2,
            items: HAIR_RESOURCES,
        },
        {
            level: 3,
            items: CLOTHES_RESOURCES,
        },
        {
            level: 4,
            items: HATS_RESOURCES,
        },
        {
            level: 5,
            items: ACCESSORIES_RESOURCES,
        },
    ],
};
